# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x05greet\"\x15\n\x05Hello\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x19\n\x06Result\x12\x0f\n\x07message\x18\x01 \x01(\t22\n\x05Greet\x12)\n\x08SayHello\x12\x0c.greet.Hello\x1a\r.greet.Result\"\x00\x42\rZ\x0bmodel/greetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013model/greet'
  _globals['_HELLO']._serialized_start=22
  _globals['_HELLO']._serialized_end=43
  _globals['_RESULT']._serialized_start=45
  _globals['_RESULT']._serialized_end=70
  _globals['_GREET']._serialized_start=72
  _globals['_GREET']._serialized_end=122
# @@protoc_insertion_point(module_scope)
